apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  resourceNames: [{{ .Release.Name }}-secret]
  verbs: ["get"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  resourceNames: [{{ .Release.Name }}-config]
  verbs: ["get"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/log"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "inarix-kutt.serviceAccountName" . }}
  namespace: default
